### ISSUE TITLE
(Line 92): Could not generate wp-config.php file

### ISSUE THREAD

**Issue by gustavoelizalde** [Pushplaybang/wordpress-docker-local-environment#2]
I'm getting this error message from the console:

php_1      | => (Line 92): Could not generate wp-config.php file.

And when I go to localhost on my browser there's a 403 Forbidden error.

What can be the problem?

**Comment by Pushplaybang** [comment]
Hey there - thanks for the feedback! 

What environment are you running this in?

**Comment by gustavoelizalde** [comment]
Hi!,

I'm using macOS Sierra 10.12.3

**Comment by Pushplaybang** [comment]
Hey There @gustavoelizalde 

These issues should now be resolved, had some sillyness in the .env file, which I've now tested thoroughly, you'll need to get the latest version from this repo, and then run the following:

``sh
docker-compose kill && docker-compose rm -v && docker-compose up --build
```

**Comment by Pushplaybang** [comment]
Closing for now, let me know if you have any further issues, really appreciate the feedback on this project.
