### ISSUE TITLE
nginx exited with code 1

### ISSUE THREAD

**Issue by shaunw** [Pushplaybang/wordpress-docker-local-environment#3]
## Ran
docker-compose build
docker-compose up

## Got
nginx_1    | /docker-entrypoint.sh: running /docker-entrypoint-init.d/wordpress-nginx.sh
nginx_1    | nginx: [emerg] no port in upstream "backend" in /etc/nginx/conf.d/wordpress.conf:83
freshwp1_nginx_1 exited with code 1

everything but nginx is running

**Comment by Pushplaybang** [comment]
@shaunw had some minor issues in the way variables were used in the .env file, this should now be resolved.  note you'll need to bin and restore your environment, run the following:

```sh
docker-compose kill && docker-compose rm -v && docker-compose up --build
```

Thanks for the feedback! Closing for now, if this is not resolved on your end, please let me know.
